const KEY='ederstone-pos-v2';
const MENU=[
['Chicken Pilau','Mains',650],['Beef Pilau','Mains',650],['Chicken Biryani','Mains',750],['Beef Biryani','Mains',800],['Chicken Curry','Mains',700],['Beef Stew','Mains',650],['Fish & Chips','Mains',700],['Chicken Burger','Burgers',550],['Beef Burger','Burgers',600],['Cheese Burger','Burgers',650],['Club Sandwich','Fast Food',500],['Chicken Shawarma','Fast Food',450],['Beef Shawarma','Fast Food',500],['Chips Plain','Sides',200],['Chips Masala','Sides',300],['Ugali & Sukuma','Local',300],['Ugali & Beef','Local',550],['Githeri Special','Local',350],['Mukimo & Beef','Local',550],['Beef Samosa','Starters',120],['Chicken Wings','Starters',450],['Beef Sausage','Starters',180],['Vegetable Spring Rolls','Starters',250],['Fresh Passion Juice','Drinks',180],['Fresh Mango Juice','Drinks',180],['Fresh Sugarcane Juice','Drinks',200],['Soda 500ml','Drinks',100],['Bottled Water','Drinks',80],['Tea','Drinks',100],['Coffee','Drinks',150],['Chai Latte','Drinks',220],['Fruit Salad','Desserts',250],['Ice Cream','Desserts',220],['Chocolate Cake','Desserts',300],['Mandazi','Breakfast',80],['Spanish Omelette','Breakfast',350],['Pancakes','Breakfast',300],['Full Breakfast','Breakfast',500]];
const seed={settings:{name:'Ederstone Restaurant',tax:0,service:0},tables:Array.from({length:16},(_,i)=>({id:i+1,status:'Open',order:[]})),menu:MENU,inventory:[['Rice','kg',32,10],['Chicken','kg',18,6],['Beef','kg',22,7],['Cooking Oil','L',20,5],['Potatoes','kg',45,12],['Passion','kg',8,4],['Mango','kg',12,4],['Soda','bottles',48,12],['Flour','kg',30,8],['Sugar','kg',18,5]],staff:[['Stone','Owner','Active'],['Cashier 01','Cashier','Active'],['Kitchen 01','Kitchen','Active'],['Waiter 01','Waiter','Active']],orders:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(seed),cart=[],activeTable=null,orderType='Takeaway',payment='Cash',category='All';
const app=document.getElementById('app'),money=n=>'KSh '+Math.round(Number(n)||0).toLocaleString('en-KE'),save=()=>localStorage.setItem(KEY,JSON.stringify(db));
function toast(m){let t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2200)}
function shell(title,sub,body){app.innerHTML='<section class="content"><div class="title-row"><div><div class="eyebrow">EDERSTONE / RESTAURANT POS</div><h1 class="title">'+title+'</h1><p class="sub">'+sub+'</p></div></div>'+body+'</section>'}
function dashboard(){let sales=db.orders.reduce((a,o)=>a+o.total,0);shell('Command Center','Everything your restaurant needs at a glance.','<div class="grid"><div class="stat"><small>TODAY SALES</small><strong>'+money(sales)+'</strong><em>Live register</em></div><div class="stat"><small>ORDERS</small><strong>'+db.orders.length+'</strong><em>Completed</em></div><div class="stat"><small>BUSY TABLES</small><strong>'+db.tables.filter(t=>t.status==='Busy').length+'/16</strong><em>Dining floor</em></div><div class="stat"><small>MENU ITEMS</small><strong>'+db.menu.length+'</strong><em>Ready to sell</em></div></div><div class="two"><div class="panel"><div class="section-head"><h3>Quick sale</h3></div><div class="actions"><button class="action primary" onclick="newOrder()">＋ New order</button><button class="action" onclick="view(\'tables\')">▥ Open tables</button><button class="action" onclick="view(\'kitchen\')">♨ Kitchen</button></div></div><div class="panel"><div class="section-head"><h3>Recent orders</h3></div><div class="list">'+(db.orders.slice(-5).reverse().map(o=>'<div class="order-card"><div class="order-line"><b>'+o.id+'</b><strong>'+money(o.total)+'</strong></div><span class="muted">'+o.type+' · '+o.payment+'</span></div>').join('')||'<p class="muted">No sales yet.</p>')+'</div></div></div>')}
function tables(){shell('Tables','Tap any table to open its live ticket.','<div class="table-grid">'+db.tables.map(t=>'<div class="table-card '+(t.status==='Busy'?'busy':'open')+'" onclick="openTable('+t.id+')"><h4>Table '+t.id+'</h4><span class="badge '+(t.status==='Busy'?'warn':'good')+'">'+t.status+'</span><p class="muted">'+(t.order.length?t.order.reduce((a,x)=>a+x.qty,0)+' items · '+money(t.order.reduce((a,x)=>a+x.price*x.qty,0)):'Available')+'</p></div>').join('')+'</div>')}
function newOrder(){activeTable=null;cart=[];orderType='Takeaway';payment='Cash';orderView()}
function openTable(id){activeTable=id;orderType='Dine-in';cart=structuredClone(db.tables[id-1].order);orderView()}
function menuCards(items){return items.map((x)=>{let i=db.menu.indexOf(x);return '<div class="item" onclick="addItem('+i+')"><div class="category">'+x[1]+'</div><div class="item-line"><b>'+x[0]+'</b><span class="price">'+money(x[2])+'</span></div><small>Tap to add</small></div>'}).join('')}
function orderView(){let cats=['All',...new Set(db.menu.map(x=>x[1]))],filtered=category==='All'?db.menu:db.menu.filter(x=>x[1]===category);shell('New Order',activeTable?'Table '+activeTable:'Walk-in / takeaway','<div class="order-layout"><div class="panel"><div class="order-tools"><input class="search" id="menuSearch" placeholder="Search '+db.menu.length+' menu items..."><div class="chips">'+cats.map(c=>'<button class="filter '+(category===c?'active':'')+'" onclick="setCategory(\''+c.replace(/'/g,"\\'")+'\')">'+c+'</button>').join('')+'</div></div><div class="menu-grid" id="menuGrid">'+menuCards(filtered)+'</div></div><div class="panel cart"><div class="section-head"><h3>Current Ticket</h3><button class="action" onclick="clearCart()">Clear</button></div><div class="chips"><button class="filter '+(orderType==='Takeaway'?'active':'')+'" onclick="setType(\'Takeaway\')">Takeaway</button><button class="filter '+(orderType==='Dine-in'?'active':'')+'" onclick="setType(\'Dine-in\')">Dine-in</button><button class="filter '+(orderType==='Delivery'?'active':'')+'" onclick="setType(\'Delivery\')">Delivery</button></div>'+(cart.map((x,i)=>'<div class="cart-row"><div><b>'+x.name+'</b><div class="muted">'+money(x.price)+' × '+x.qty+'</div></div><div class="qty"><button onclick="changeQty('+i+',-1)">−</button><b>'+x.qty+'</b><button onclick="changeQty('+i+',1)">+</button></div></div>').join('')||'<p class="muted">Your ticket is empty. Tap food items.</p>')+'<div class="totals"><div>Subtotal <b>'+money(subtotal())+'</b></div><div>Tax <b>'+money(subtotal()*db.settings.tax/100)+'</b></div><div>Service <b>'+money(subtotal()*db.settings.service/100)+'</b></div><strong>Total <b>'+money(grand())+'</b></strong></div><div class="pay-grid">'+['Cash','M-Pesa','Card','Split'].map(p=>'<button class="pay-btn '+(payment===p?'selected':'')+'" onclick="setPay(\''+p+'\')">'+p+'</button>').join('')+'</div><button class="action primary big" onclick="checkout()">Complete & Pay '+money(grand())+'</button></div></div>');document.getElementById('menuSearch').oninput=e=>{let q=e.target.value.toLowerCase();document.getElementById('menuGrid').innerHTML=menuCards(filtered.filter(x=>x[0].toLowerCase().includes(q)))}}
function subtotal(){return cart.reduce((a,x)=>a+x.price*x.qty,0)}function grand(){return subtotal()*(1+db.settings.tax/100+db.settings.service/100)}
function addItem(i){let x=db.menu[i],f=cart.find(c=>c.name===x[0]);f?f.qty++:cart.push({name:x[0],price:x[2],qty:1});syncTable();orderView();toast(x[0]+' added')}
function changeQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);syncTable();orderView()}
function syncTable(){if(activeTable){let t=db.tables[activeTable-1];t.order=structuredClone(cart);t.status=cart.length?'Busy':'Open';save()}}
function clearCart(){cart=[];syncTable();orderView()}
function setCategory(c){category=c;orderView()}function setType(t){orderType=t;orderView()}function setPay(p){payment=p;orderView()}
function checkout(){if(!cart.length)return toast('Add food before payment');let o={id:'ORD-'+Date.now().toString().slice(-6),table:activeTable,type:orderType,payment,total:grand(),subtotal:subtotal(),items:structuredClone(cart),status:'Paid',time:new Date().toLocaleString()};db.orders.push(o);if(activeTable){db.tables[activeTable-1].order=[];db.tables[activeTable-1].status='Open'}cart=[];activeTable=null;save();showReceipt(o);view('dashboard')}
function showReceipt(o){let m=document.getElementById('modal'),b=document.getElementById('modalBox');b.innerHTML='<div class="section-head"><h3>Receipt '+o.id+'</h3><button class="action" onclick="modal.classList.remove(\'show\')">Close</button></div><div class="receipt"><h2>'+db.settings.name+'</h2><p>'+o.time+'<br>'+o.type+(o.table?' · Table '+o.table:'')+'</p><hr>'+o.items.map(x=>'<div class="order-line"><span>'+x.name+' ×'+x.qty+'</span><b>'+money(x.price*x.qty)+'</b></div>').join('')+'<hr><div class="order-line"><b>SUBTOTAL</b><b>'+money(o.subtotal)+'</b></div><div class="order-line"><b>TOTAL</b><b>'+money(o.total)+'</b></div><p>Payment: '+o.payment+'</p><center>Thank you. Come again.</center></div><button class="action primary big" onclick="window.print()">Print receipt</button>';m.classList.add('show')}
function orders(){shell('Orders','Every completed transaction is recorded locally.','<div class="list">'+(db.orders.slice().reverse().map(o=>'<div class="order-card"><div class="order-line"><b>'+o.id+'</b><strong>'+money(o.total)+'</strong></div><div class="muted">'+o.time+' · '+o.type+' · '+o.payment+(o.table?' · Table '+o.table:'')+'</div><button class="action" onclick="showReceipt('+JSON.stringify(o).replace(/"/g,'&quot;')+')">View receipt</button></div>').join('')||'<p class="muted">No completed orders.</p>')+'</div>')}
function kitchen(){let tickets=db.tables.filter(t=>t.status==='Busy');shell('Kitchen Display','Live food tickets from occupied tables.','<div class="grid">'+(tickets.map(t=>'<div class="panel"><div class="section-head"><h3>Table '+t.id+'</h3><span class="badge warn">COOKING</span></div>'+t.order.map(x=>'<div class="cart-row"><span>'+x.name+'</span><b>×'+x.qty+'</b></div>').join('')+'<button class="action primary" onclick="markReady('+t.id+')">Mark ready</button></div>').join('')||'<p class="muted">Kitchen clear. New dine-in tickets appear here.</p>')+'</div>')}
function markReady(id){db.tables[id-1].status='Open';db.tables[id-1].order=[];save();view('kitchen');toast('Table '+id+' ready')}
function menu(){shell('Menu Manager','Your live catalogue contains '+db.menu.length+' food and drink items.','<div class="panel"><div class="section-head"><h3>Menu catalogue</h3><button class="action primary" onclick="addMenu()">＋ Add item</button></div><div class="menu-grid">'+db.menu.map((x,i)=>'<div class="item"><div class="category">'+x[1]+'</div><div class="item-line"><b>'+x[0]+'</b><strong>'+money(x[2])+'</strong></div><button class="action" onclick="editMenu('+i+')">Edit</button></div>').join('')+'</div></div>')}
function addMenu(){let n=prompt('Food/drink name');if(!n)return;let p=Number(prompt('Price in KSh'));if(!p)return;let c=prompt('Category','Mains')||'Mains';db.menu.push([n,c,p]);save();view('menu')}
function editMenu(i){let p=Number(prompt('New price for '+db.menu[i][0],db.menu[i][2]));if(p){db.menu[i][2]=p;save();view('menu')}}
function inventory(){shell('Inventory','Monitor stock and reorder points.','<div class="list">'+db.inventory.map((x,i)=>'<div class="item"><div class="item-line"><b>'+x[0]+'</b><strong>'+x[2]+' '+x[1]+'</strong></div><div class="muted">Reorder at '+x[3]+' '+x[1]+'</div><div class="actions"><button class="action" onclick="stock('+i+',-1)">− 1</button><button class="action" onclick="stock('+i+',1)">＋ 1</button></div></div>').join('')+'</div>')}
function stock(i,d){db.inventory[i][2]=Math.max(0,db.inventory[i][2]+d);save();view('inventory')}
function staff(){shell('Staff','Roles for the restaurant team.','<div class="list">'+db.staff.map(x=>'<div class="item"><div class="item-line"><b>'+x[0]+'</b><span class="badge good">'+x[2]+'</span></div><span class="muted">'+x[1]+'</span></div>').join('')+'</div>')}
function reports(){let s=db.orders.reduce((a,o)=>a+o.total,0);shell('Reports','Sales performance from this register.','<div class="grid"><div class="stat"><small>GROSS SALES</small><strong>'+money(s)+'</strong></div><div class="stat"><small>AVERAGE TICKET</small><strong>'+money(db.orders.length?s/db.orders.length:0)+'</strong></div><div class="stat"><small>M-PESA</small><strong>'+money(db.orders.filter(o=>o.payment==='M-Pesa').reduce((a,o)=>a+o.total,0))+'</strong></div><div class="stat"><small>CASH</small><strong>'+money(db.orders.filter(o=>o.payment==='Cash').reduce((a,o)=>a+o.total,0))+'</strong></div></div>')}
function settings(){shell('Settings','Configure the register.','<div class="panel"><div class="form-grid"><div class="field"><label>RESTAURANT NAME</label><input id="rn" value="'+db.settings.name+'"></div><div class="field"><label>TAX %</label><input id="tx" type="number" value="'+db.settings.tax+'"></div><div class="field"><label>SERVICE %</label><input id="sv" type="number" value="'+db.settings.service+'"></div></div><div class="actions"><button class="action primary" onclick="saveSettings()">Save settings</button><button class="action" onclick="resetPOS()">Reset POS data</button></div></div>')}
function saveSettings(){db.settings.name=document.getElementById('rn').value||'Ederstone Restaurant';db.settings.tax=Number(document.getElementById('tx').value)||0;db.settings.service=Number(document.getElementById('sv').value)||0;save();toast('Settings saved');view('settings')}
function resetPOS(){if(confirm('Reset all POS data?')){db=structuredClone(seed);save();view('dashboard')}}
function view(v){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===v));({dashboard,tables,orders,menu,kitchen,inventory,staff,reports,settings}[v]||dashboard)()}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>view(n.dataset.view));document.getElementById('logoutPos').onclick=()=>location.href='projects.html';setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),1000);view('dashboard');